-- 코드를 입력하세요
# SELECT COUNT(DISTINCT NAME) COUNT
# FROM ANIMAL_INS
# WHERE NAME IS NOT NULL

SELECT COUNT(*) COUNT
FROM ANIMAL_INS
WHERE ANIMAL_ID IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    GROUP BY NAME
    HAVING NAME IS NOT NULL
)