-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) SALES
FROM PRODUCT P
    INNER JOIN OFFLINE_SALE O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE









# SELECT P.PRODUCT_CODE, SUM(O.SALES_AMOUNT * P.PRICE) SALES
# FROM PRODUCT P 
#     INNER JOIN OFFLINE_SALE O
#     ON P.PRODUCT_ID = O.PRODUCT_ID
# GROUP BY P.PRODUCT_CODE
# ORDER BY SALES DESC, PRODUCT_CODE;