-- 코드를 입력하세요
# SELECT ANIMAL_TYPE, NAME, SEX_UPON_INTAKE
# FROM ANIMAL_INS
# WHERE NAME IS NOT NULL

# UNION ALL

# SELECT ANIMAL_TYPE, 'No name' NAME, SEX_UPON_INTAKE
# FROM ANIMAL_INS
# WHERE NAME IS NULL

SELECT ANIMAL_TYPE, IFNULL(NAME, 'No name'), SEX_UPON_INTAKE
FROM ANIMAL_INS