-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I
    RIGHT OUTER JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL





# SELECT B.ANIMAL_ID, B.NAME
# FROM ANIMAL_INS A
# RIGHT JOIN ANIMAL_OUTS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE A.ANIMAL_ID IS NULL