-- 코드를 입력하세요
SELECT 
    '2022' YEAR, 
    SUBSTRING(O.SALES_DATE, 6, 2) MONTH, 
    COUNT(DISTINCT O.USER_ID) PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(DISTINCT USER_ID) 
                                     FROM USER_INFO 
                                     WHERE YEAR(JOINED) = '2021'
                                    ), 1) PURCHASED_RATIO
FROM USER_INFO I
    INNER JOIN ONLINE_SALE O
    ON I.USER_ID = O.USER_ID
WHERE JOINED REGEXP('^2021')
GROUP BY SUBSTRING(O.SALES_DATE, 6, 2)
ORDER BY YEAR, MONTH

# SELECT
# YEAR(SALES_DATE) AS YEAR,
# MONTH(SALES_DATE) AS MONTH,
# COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS,
# ROUND(COUNT(DISTINCT os.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = "2021"), 1) AS PURCHASED_RATIO
# FROM USER_INFO ui
# INNER JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID 
# WHERE YEAR(JOINED) LIKE "2021"
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)