-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) TOTAL_SALES
FROM FOOD_PRODUCT P
    INNER JOIN FOOD_ORDER O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05=31'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID









# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) TOTAL_SALES
# FROM FOOD_PRODUCT P
#     INNER JOIN FOOD_ORDER O
#     ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
# GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
# ORDER BY TOTAL_SALES DESC, PRODUCT_ID;