-- 코드를 입력하세요
# SELECT F.FLAVOR
# FROM FIRST_HALF F
#     INNER JOIN JULY J
#     ON F.SHIPMENT_ID = J.SHIPMENT_ID
# GROUP BY FLAVOR
# ORDER BY 
SELECT FLAVOR
FROM (
    SELECT * FROM FIRST_HALF
    UNION ALL
    SELECT * FROM JULY
) A
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3