-- 코드를 입력하세요
SELECT I.INGREDIENT_TYPE, SUM(H.TOTAL_ORDER) TOTAL_ORDER
FROM ICECREAM_INFO I
    INNER JOIN FIRST_HALF H
    ON I.FLAVOR = H.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER
-- WHERE FLAVOR REGEXP ('L$|^E|^V')